
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Seller.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Bil
{

    public string billID { get; set; }

    public string uID { get; set; }

    public string pID { get; set; }

}

}
